import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import QuickFilter from '../components/QuickFilter'
import Showcase from '../components/Shawcase'
import Footer from '../components/Footer'




import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Hero />
      <Showcase />
      <Head>
        <title>YCode food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Footer/>

    </div>
  )
}
